name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install tailwindcss and deps
        run: |
          npm install -g tailwindcss
          npm install @tailwindcss/forms

      - name: Clean
        run: make clean

      - name: Build CSS
        run: make css

      - name: Build
        run: make
